security:
 basic:
  enabled: false # turn off securing our application endpoints
management:
 security:
logging: # <----New sections below
 level:
  io:
   pivotal: DEBUG
greeting:
 displayFortune: false
quoteServiceURL: http://quote-service-dev.cfapps.io/quote
   
